name: Test Project
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout?version=v4.2.1
      - name: Get the code from the repo
        uses: actions/checkout@v4.2.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test