name: Test Project
on:
  push:
    branches: [ "test", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v4.2.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Maven Test
        run: mvn test
